/*
char json_str[] =

"{\n"
"        \"sender\":\"supercap\",\n"
"        \"receiver\":\"Broker\",\n"
"        \"hw_id\":\"XXYYZZ0002\",\n"
"        \"message_id\":\"PER_DT\",\n"
"        \"group_id\":\"a93cf2ff-2a0a-4992-bb54-cc8bdeed1902\",\n"
"        \"state\":\"OPERN\",\n"
"        \"timestamp\":\"1699947499\",\n"
"        \"data\":{\n"
"                \"max_charging_current\":\"10 Amp\",\n"
"                \"over_voltage_cutoff\":\"24 Volts\",\n"
"                \"iState\":\"test\",\n"
"                \"max_capacity\":\"Max Capacity\",\n"
"                \"capacitor_data\":[\n"
"							{\n"
"                                                \"voltage\":\"2\",\n"
"                                                \"temperature\":\"39\"\n"
"                                        },\n"
"							{\n"
"                                                \"voltage\":\"1\",\n"
"                                                \"temperature\":\"43\"\n"
"                                        },\n"
"							{\n"
"                                                \"voltage\":\"2\",\n"
"                                                \"temperature\":\"22\"\n"
"                                        },\n"
"							{\n"
"                                                \"voltage\":\"0\",\n"
"                                                \"temperature\":\"40\"\n"
"                                        },\n"
"							{\n"
"                                                \"voltage\":\"1\",\n"
"                                                \"temperature\":\"48\"\n"
"                                        },\n"
"							{\n"
"                                                \"voltage\":\"1\",\n"
"                                                \"temperature\":\"40\"\n"
"                                        }],\n"
"                \"max_charging_current\":\"10 Amp\",\n"
"                \"input_overcurrent_threshold\":\"71 Amp\",\n"
"                \"output_overcurrent_threshold\":\"206 Amp\",\n"
"                \"discharging_current_limit\":\"71 Amp\",\n"
"                \"over_temperature_threshold\":\"81 degreeC\",\n"
"                \"cell_balancing_threshold\":\"3V\",\n"
"                \"dawdle_voltage_limit\":\"DawdleVoltageLimit\",\n"
"                \"network_ip_mode\":\"DHCP/STATIC\",\n"
"                \"device_static_ip\":\"10.10.10.5\",\n"
"                \"netmask\":\"255.255.255.0\",\n"
"                \"device_ip\":\"10.10.10.5\",\n"
"                \"lifetime_max_capacitor_voltage\":\"2.9V\",\n"
"                \"lifetime_max_temperature\":\"81 degreeC\",\n"
"                \"lifetime_min_temperature\":\"74 degreeC\",\n"
"                \"slave_control_parameters\":\"Slave Control Parameters\",\n"
"                \"SystemInfo\":{\n"
"                                \"system_name\":\"System Name\",\n"
"                                \"part_number\":\"part number\",\n"
"                                \"HW_ID\":\"Product ID\",\n"
"                                \"factory_leaving_date\":\"DD-MM-YYYY\",\n"
"                                \"sw_version_number\":\"v1.0\",\n"
"                                \"sw_version_slaves\":\"v1.0.0\",\n"
"                                \"group_roll_number\":\"123-456-789\"\n"
"                        }\n"
"        }\n"
"}\n"
"";
*/

char json_str[] = "{\n"
"\"sender\": \"ui\",\n"
"\"receiver\": \"supercap\",\n"
"\"message_id\": \"CON_DT\",\n"
"\"group_id:\": \"abcd1234efgh5678\",\n"
"\"group_roll_number\": \"01\",\n"
"\"hw_id:\": \"XXYYZZNNNN\",\n"
"\"state\": \"OPERN\",\n"
"\"timestamp\": \"1699947499\",\n"
"\n"
"\"data\": {\n"
"\t\"bank_voltage_limit\": \"0-168V\",\n"
"\t\"charging_voltage_limit\": \"0-50A\",\n"
"\t\"charging_current_limit\": \"0-50A\",\n"
"\t\"discharging_current_limit\": \"0-130A\",\n"
"\t\"over_temperature_limit\": \"65 - 85 degrees C\",\n"
"\t\"cell_balancing_threshold\": \"Cellbalancingthreshold\"\n"
"\t}\n"
"\n"
"} ";
